[tool.poetry]
name = "crowemi-trades"
version = "0.1.0"
description = ""
authors = ["crowemi <crowemi@hotmail.com>"]
readme = "README.md"
packages = [{include = "crowemi_trade"}]

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.26.52"
polygon-api-client = "^1.6.1"
smart-open = "^6.3.0"
polars = "^0.15.16"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
