name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install TA-lib pre-reqs
        run: sudo apt-get install build-essential &&
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz &&
          tar -xzf ta-lib-0.4.0-src.tar.gz &&
          cd ta-lib/ &&
          ./configure --prefix=/usr &&
          make &&
          sudo make install
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install Dependencies
        run: poetry install --with dev

      - name: Start LocalStack
        run: |
          pip install localstack awscli-local[ver1] # install LocalStack cli and awslocal
          docker pull localstack/localstack         # Make sure to pull the latest version of the image
          localstack start -d                       # Start LocalStack in the background

          echo "Waiting for LocalStack startup..."  # Wait 30 seconds for the LocalStack container
          localstack wait -t 30                     # to become ready before timing out 
          echo "Startup complete"

      - name: Run tests
        run: |
          python -m unittest &&
          coverage run -m unittest discover
