name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install TA-lib pre-reqs
        run:
          sudo apt-get install build-essential &&
          sudo wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz &&
          sudo tar -xzf ta-lib-0.4.0-src.tar.gz &&
          cd ta-lib/ &&
          sudo ./config &&
          sudo make &&
          sudo make install
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2
          virtualenvs-create: false
          virtualenvs-in-project: false

      - name: Install Dependencies
        run: poetry install --with dev
